[package]
name = "olympus-verifier"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
olympus-spanned.workspace = true
olympus-parser.workspace = true

[lints]
workspace = true
