[package]
name = "olympus-lexer"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
ariadne.workspace = true
unicode-segmentation.workspace = true

[lints]
workspace = true
