[package]
name = "olympus-lexer"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
olympus-spanned.workspace = true

unicode-segmentation.workspace = true

[lints]
workspace = true
