[package]
name = "olympus-net-common"
edition.workspace = true
version.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5"
paste = "1"

[lints]
workspace = true
