[package]
name = "olympus"
edition.workspace = true
version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ariadne.workspace = true
unicode-segmentation.workspace = true
