[package]
name = "olympus-parser"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
olympus-common.workspace = true
olympus-lexer.workspace = true

[lints]
workspace = true
