[package]
name = "example-client"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
olympus-client.workspace = true
olympus-net-common.workspace = true
common = { path = "../common" }
tokio.workspace = true

[lints]
workspace = true
