name: build
on:
  push:

jobs:
  build-and-test:
    runs-on: olympus-runner-set
    steps:
      - run: sudo apt update && sudo apt install -yyqq curl clang
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --all
      - run: cargo test --all
